/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GdkPixbuf *window1_icon_pixbuf;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *seven;
  GtkWidget *division;
  GtkWidget *multiplication;
  GtkWidget *substraction;
  GtkWidget *dot;
  GtkWidget *equal;
  GtkWidget *plusminus;
  GtkWidget *clear;
  GtkWidget *CE;
  GtkWidget *backspace;
  GtkWidget *addition;
  GtkWidget *eight;
  GtkWidget *nine;
  GtkWidget *four;
  GtkWidget *five;
  GtkWidget *six;
  GtkWidget *one;
  GtkWidget *two;
  GtkWidget *three;
  GtkWidget *zero;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (window1), 8);
  gtk_window_set_title (GTK_WINDOW (window1), _("My Calculator"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (window1), TRUE);
  window1_icon_pixbuf = create_pixbuf ("403248.jpg");
  if (window1_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window1), window1_icon_pixbuf);
      gdk_pixbuf_unref (window1_icon_pixbuf);
    }

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 8, 32);
  gtk_widget_set_size_request (entry1, 312, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  seven = gtk_button_new_with_mnemonic (_("7"));
  gtk_widget_show (seven);
  gtk_fixed_put (GTK_FIXED (fixed1), seven, 8, 136);
  gtk_widget_set_size_request (seven, 72, 32);

  division = gtk_button_new_with_mnemonic (_("\303\267"));
  gtk_widget_show (division);
  gtk_fixed_put (GTK_FIXED (fixed1), division, 248, 136);
  gtk_widget_set_size_request (division, 72, 32);

  multiplication = gtk_button_new_with_mnemonic (_("\303\227"));
  gtk_widget_show (multiplication);
  gtk_fixed_put (GTK_FIXED (fixed1), multiplication, 248, 176);
  gtk_widget_set_size_request (multiplication, 72, 32);

  substraction = gtk_button_new_with_mnemonic (_("-"));
  gtk_widget_show (substraction);
  gtk_fixed_put (GTK_FIXED (fixed1), substraction, 248, 216);
  gtk_widget_set_size_request (substraction, 71, 32);

  dot = gtk_button_new_with_mnemonic (_("."));
  gtk_widget_show (dot);
  gtk_fixed_put (GTK_FIXED (fixed1), dot, 88, 256);
  gtk_widget_set_size_request (dot, 70, 32);

  equal = gtk_button_new_with_mnemonic (_("="));
  gtk_widget_show (equal);
  gtk_fixed_put (GTK_FIXED (fixed1), equal, 168, 256);
  gtk_widget_set_size_request (equal, 72, 32);

  plusminus = gtk_button_new_with_mnemonic (_("\302\261"));
  gtk_widget_show (plusminus);
  gtk_fixed_put (GTK_FIXED (fixed1), plusminus, 248, 96);
  gtk_widget_set_size_request (plusminus, 72, 32);

  clear = gtk_button_new_with_mnemonic (_("Clr"));
  gtk_widget_show (clear);
  gtk_fixed_put (GTK_FIXED (fixed1), clear, 168, 96);
  gtk_widget_set_size_request (clear, 72, 32);

  CE = gtk_button_new_with_mnemonic (_("CE"));
  gtk_widget_show (CE);
  gtk_fixed_put (GTK_FIXED (fixed1), CE, 88, 96);
  gtk_widget_set_size_request (CE, 72, 32);

  backspace = gtk_button_new_with_mnemonic (_("Bksp"));
  gtk_widget_show (backspace);
  gtk_fixed_put (GTK_FIXED (fixed1), backspace, 8, 96);
  gtk_widget_set_size_request (backspace, 72, 32);

  addition = gtk_button_new_with_mnemonic (_("+"));
  gtk_widget_show (addition);
  gtk_fixed_put (GTK_FIXED (fixed1), addition, 248, 256);
  gtk_widget_set_size_request (addition, 72, 32);

  eight = gtk_button_new_with_mnemonic (_("8"));
  gtk_widget_show (eight);
  gtk_fixed_put (GTK_FIXED (fixed1), eight, 88, 136);
  gtk_widget_set_size_request (eight, 72, 32);

  nine = gtk_button_new_with_mnemonic (_("9"));
  gtk_widget_show (nine);
  gtk_fixed_put (GTK_FIXED (fixed1), nine, 168, 136);
  gtk_widget_set_size_request (nine, 72, 32);

  four = gtk_button_new_with_mnemonic (_("4"));
  gtk_widget_show (four);
  gtk_fixed_put (GTK_FIXED (fixed1), four, 8, 176);
  gtk_widget_set_size_request (four, 72, 32);

  five = gtk_button_new_with_mnemonic (_("5"));
  gtk_widget_show (five);
  gtk_fixed_put (GTK_FIXED (fixed1), five, 88, 176);
  gtk_widget_set_size_request (five, 72, 32);

  six = gtk_button_new_with_mnemonic (_("6"));
  gtk_widget_show (six);
  gtk_fixed_put (GTK_FIXED (fixed1), six, 168, 176);
  gtk_widget_set_size_request (six, 72, 32);

  one = gtk_button_new_with_mnemonic (_("1"));
  gtk_widget_show (one);
  gtk_fixed_put (GTK_FIXED (fixed1), one, 8, 216);
  gtk_widget_set_size_request (one, 72, 32);

  two = gtk_button_new_with_mnemonic (_("2"));
  gtk_widget_show (two);
  gtk_fixed_put (GTK_FIXED (fixed1), two, 88, 216);
  gtk_widget_set_size_request (two, 70, 32);

  three = gtk_button_new_with_mnemonic (_("3"));
  gtk_widget_show (three);
  gtk_fixed_put (GTK_FIXED (fixed1), three, 168, 216);
  gtk_widget_set_size_request (three, 72, 32);

  zero = gtk_button_new_with_mnemonic (_("0"));
  gtk_widget_show (zero);
  gtk_fixed_put (GTK_FIXED (fixed1), zero, 8, 256);
  gtk_widget_set_size_request (zero, 72, 32);

  g_signal_connect ((gpointer) seven, "clicked",
                    G_CALLBACK (on_seven_clicked),
                    NULL);
  g_signal_connect ((gpointer) division, "clicked",
                    G_CALLBACK (on_division_clicked),
                    NULL);
  g_signal_connect ((gpointer) multiplication, "clicked",
                    G_CALLBACK (on_multiplication_clicked),
                    NULL);
  g_signal_connect ((gpointer) substraction, "clicked",
                    G_CALLBACK (on_substraction_clicked),
                    NULL);
  g_signal_connect ((gpointer) dot, "clicked",
                    G_CALLBACK (on_dot_clicked),
                    NULL);
  g_signal_connect ((gpointer) equal, "clicked",
                    G_CALLBACK (on_equal_clicked),
                    NULL);
  g_signal_connect ((gpointer) plusminus, "clicked",
                    G_CALLBACK (on_plusminus_clicked),
                    NULL);
  g_signal_connect ((gpointer) clear, "clicked",
                    G_CALLBACK (on_clear_clicked),
                    NULL);
  g_signal_connect ((gpointer) CE, "clicked",
                    G_CALLBACK (on_CE_clicked),
                    NULL);
  g_signal_connect ((gpointer) backspace, "clicked",
                    G_CALLBACK (on_backspace_clicked),
                    NULL);
  g_signal_connect ((gpointer) addition, "clicked",
                    G_CALLBACK (on_addition_clicked),
                    NULL);
  g_signal_connect ((gpointer) eight, "clicked",
                    G_CALLBACK (on_eight_clicked),
                    NULL);
  g_signal_connect ((gpointer) nine, "clicked",
                    G_CALLBACK (on_nine_clicked),
                    NULL);
  g_signal_connect ((gpointer) four, "clicked",
                    G_CALLBACK (on_four_clicked),
                    NULL);
  g_signal_connect ((gpointer) five, "clicked",
                    G_CALLBACK (on_five_clicked),
                    NULL);
  g_signal_connect ((gpointer) six, "clicked",
                    G_CALLBACK (on_six_clicked),
                    NULL);
  g_signal_connect ((gpointer) one, "clicked",
                    G_CALLBACK (on_one_clicked),
                    NULL);
  g_signal_connect ((gpointer) two, "clicked",
                    G_CALLBACK (on_two_clicked),
                    NULL);
  g_signal_connect ((gpointer) three, "clicked",
                    G_CALLBACK (on_three_clicked),
                    NULL);
  g_signal_connect ((gpointer) zero, "clicked",
                    G_CALLBACK (on_zero_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, seven, "seven");
  GLADE_HOOKUP_OBJECT (window1, division, "division");
  GLADE_HOOKUP_OBJECT (window1, multiplication, "multiplication");
  GLADE_HOOKUP_OBJECT (window1, substraction, "substraction");
  GLADE_HOOKUP_OBJECT (window1, dot, "dot");
  GLADE_HOOKUP_OBJECT (window1, equal, "equal");
  GLADE_HOOKUP_OBJECT (window1, plusminus, "plusminus");
  GLADE_HOOKUP_OBJECT (window1, clear, "clear");
  GLADE_HOOKUP_OBJECT (window1, CE, "CE");
  GLADE_HOOKUP_OBJECT (window1, backspace, "backspace");
  GLADE_HOOKUP_OBJECT (window1, addition, "addition");
  GLADE_HOOKUP_OBJECT (window1, eight, "eight");
  GLADE_HOOKUP_OBJECT (window1, nine, "nine");
  GLADE_HOOKUP_OBJECT (window1, four, "four");
  GLADE_HOOKUP_OBJECT (window1, five, "five");
  GLADE_HOOKUP_OBJECT (window1, six, "six");
  GLADE_HOOKUP_OBJECT (window1, one, "one");
  GLADE_HOOKUP_OBJECT (window1, two, "two");
  GLADE_HOOKUP_OBJECT (window1, three, "three");
  GLADE_HOOKUP_OBJECT (window1, zero, "zero");

  return window1;
}

